app/core/components/global/header.tsx

https://linear.app/buscorepuestos/issue/BR-562/[home]-boton-de-regreso-a-home

refactor: :zap: [BR-562] Icono de BR para volver a home

---

app/core/components/Button.tsx
app/core/components/SearchBar.tsx
app/core/components/Slider.tsx
app/core/components/cards/CardInfo.tsx
app/core/components/cards/CardPrice.tsx
app/core/components/cards/CardValoration.tsx
app/core/components/global/header.tsx
app/page.tsx

https://linear.app/buscorepuestos/issue/BR-566/[home]-mobile

style: :art: [BR-566] Estilos mobiles home

---

app/page.tsx

https://linear.app/buscorepuestos/issue/BR-565/[home]-barra-busqueda

fix: :zap: [BR-565] Fix de barra de busqueda del home

---

app/tienda/[search]/page.tsx
app/tienda/page.tsx

https://linear.app/buscorepuestos/issue/BR-568/[store]-abrir-producto

fix: :bug: [BR-568] fix de acceder a un producto despues de una busqueda

---

app/tienda/[search]/page.tsx
app/tienda/page.tsx

https://linear.app/buscorepuestos/issue/BR-580/[tienda]-optimizar-busquedas

refactor: :zap: [BR-580] Busqueda de algolia en la store con enter

---

app/core/components/__tests__/product-price.test.tsx
app/core/components/productPrice/productPrice.tsx
app/tienda/page.tsx

fix: :zap: [BR-597] fallo al añadir una compra en airtable

---

app/core/components/productPrice/productPrice.tsx
app/core/components/shopping-cart/ProductCartInfo.tsx
app/services/algolia/updateStock.service.ts
app/services/products/products.service.ts
app/verificacion-pago/page.tsx

fix: :zap: [BR-STOCK] fix de actualizacion de stock en algolia y mongo

---

app/core/components/__tests__/product-price.test.tsx
app/core/components/productPrice/productPrice.tsx
app/tienda/[search]/page.tsx

fix: :zap: [BR] fix de boton de comprar

---

app/core/components/checkout/StripeForm.tsx
app/core/components/input/input.tsx
app/core/components/paymentSelection/PaymentSelection.tsx
app/verificacion-pago/page.tsx

feat: :zap: [BR-591] interaccion con info incompleta

---

app/core/components/paymentSelection/PaymentSelection.tsx
app/core/components/transferPayment/transferPayment.tsx

fix: :zap: [BR-587] fix de diseño de transferencia

---

app/core/components/productTitle/productTitle.tsx

refactor: :art: [BR-586] refactor de boton de compartir

---

app/core/components/paymentSelection/PaymentSelection.tsx
app/layout.tsx

feat: :zap: [BR-602] google tag manager

---

app/core/components/productPrice/productPrice.tsx
app/tienda/[search]/page.tsx
app/tienda/page.tsx

fix: :zap: [BR-604] fix de tiempo en funcion de compra

---

app/core/components/cards/CardPrice.tsx
app/core/components/productPrice/productPrice.tsx
app/core/components/transferPayment/transferPayment.tsx
app/tienda/[search]/page.tsx
app/tienda/page.tsx

feat: :zap: [BR-603] loading en botones de comprar o finalizar compra

---

app/core/components/input/input.tsx
app/core/components/sumupPayment/sumupPayment.tsx

feat: :zap: [BR-607] pagos identificados en sumup con id y titulo

---

app/core/components/input/input.tsx
app/verificacion-pago/page.tsx

feat: :zap: [BR-609] funcionalidad de boton enter en correo

---

app/core/components/paymentSelection/PaymentSelection.tsx
app/services/mailchimp/mailchimp.tsx
app/services/sumup/sumupWidget.tsx
app/verificacion-pago/page.tsx

fix: :zap: fix de creacion y actualiizacion de usuario en mailchimp

---

app/tienda/[search]/page.tsx
app/tienda/page.tsx
next.config.mjs

fix: :zap: [BR-584] fix de imagenes y ordenamiento de tienda

---

app/core/components/__tests__/footer.test.tsx
app/core/components/filters/filters.tsx
app/core/components/global/footer.tsx
app/tienda/[search]/page.tsx
app/tienda/page.tsx

feat: :zap: [BR-589] filtro de tienda por año

---

app/services/sumup/sumupWidget.tsx

fix: :zap: [BR-fix] fix de sumup

---

app/core/components/productPrice/productPrice.tsx

fix: :zap: [BR-fix] fix de transferencias

---

app/services/sumup/sumupWidget.tsx
app/tienda/page.tsx

fix: :zap: [BR-fix] fix de sumup alert y scrollto en tienda

---

app/core/components/cards/CardPrice.tsx
app/core/components/filterTag/FilterTag.tsx
app/core/components/filters/filters.tsx
app/producto/[id]/page.tsx
app/tienda/page.tsx
vitest.config.ts

feat: :zap: [BR-63] mejoras de la tienda

---

app/environment/dev-environment/environment.dev-environment.ts
app/environment/dev/environment.dev.ts
app/environment/environment.ts
app/environment/release/environment.release.ts
app/tienda/[search]/page.tsx
app/tienda/page.tsx
package.json

Merge tag 'v1.5.5' into develop

---

app/page.tsx

fix: :bug: correct product ID handling in SwiperSlide component

---

app/page.tsx
app/redux/features/productSearchSlice.tsx
app/redux/store.ts
app/tienda/[search]/page.tsx
app/tienda/page.tsx

feat: :sparkles: add product search slice and integrate into Redux store

---

app/layout.tsx

Facebookj pixel

---

app/services/sumup/sumupWidget.tsx

Add initial debugging log for SumUp response handling
